SERVER: server.cpp
	@echo -------------------------------------------
	g++ server.cpp TextFunc.cpp -o server -std=c++20
	@echo -------------------------------------------
CLIENT: client.cpp
	@echo -------------------------------------------
	g++ client.cpp TextFunc.cpp -o client -std=c++20
	@echo -------------------------------------------
