#include "gtk/spotivar-glade-ui.h"

// ============================ ATTENTION ============================
// This file is AUTOMATICALLY GENERATED from spotivar.glade.cpp.m4
// And should not be edited by hand, as it will be automatically 
// updated during build, and all your changes will be DESTROYED!
// ==============> Edit spotivar.glade.cpp.m4 instead! <==============

const char *const sptv::spotivar_glade_ui = R"(include(res/spotivar.glade))";
